bubble_sort: dependency
	gcc -o bubble_sort $(SHR2)print_array.c $(SHR2)read_input.c bubble_sort.c
	./bubble_sort

dependency:
	make -C $(SHR)

SHR=../../CLang/
SHR2=$(SHR)src/
include $(SHR)makefile

